export const ROUTES = {
  home: '/',
  about: '/about',
  aboutCompany: '/about',
  branches: '/branches',
  visionAndMessage: '/about/vision-mission',
  organizationStructure: '/about/structure',
  contractsRegulation: '/about/regulations',
  companyAchievements: '/about/achievements',
  awareness: '/awareness',
  adviceAndContact: '/awareness/contact',
  cyberSecurityGuidelines: '/awareness/cyber-security',
  forKidsAndWomen: '/awareness/community-outreach',
  waterQuality: '/water-quality',
  refiningWater: '/water-quality/purification',
  labOfCompanyWater: '/water-quality/central-lab',
  labOfCompany: '/lab-of-company',
  wasteOfCompany: '/waste-of-company',
  trainingOfCompany: '/training-of-company',
  informationTechnologyOfCompany: '/it-management',
  schoolSubmissionData: '/school-submission-data',
  schoolGallery: '/school-of-company',
  sportOfCompany: '/sport-of-company',
  sanitation: '/sanitation',
  sewageTreatment: '/sanitation/treatment',
  safeSewageDisposal: '/sanitation/safe-disposal',
  saveSewageNetwork: '/sanitation/network-preservation',
  industrialWaste: '/sanitation/industrial-waste',
  industrialWasteRole: '/sanitation/industrial-waste-management',
  customerCharter: '/services/customer-charter',
  newsArchive: '/news',
  newsDetails: '/news/:id',
  projectsArchive: '/projects',
  projectDetails: '/projects/:id',
  tendersArchive: '/tenders',
  tenderDetails: '/tenders/:id',
  generalAdminTraining: '/training/administrative',
  callCenter: '/services/customer-care',
  provideRequest: '/services/inquiries',
  provideComplaine: '/services/complaints',
  hotlineApp: '/services/hotline-app',
  myReadingApp: '/services/meter-reading',
  integritySupportOverview: '/about/integrity',
  integritySupportHighlights: '/about/integrity-activities',
  professionalConduct: '/about/code-of-conduct',
  bossTrips: '/trips-the-boss',
  jobsAndCompetition: '/careers/vacancies',
  resultOfWorker: '/careers/results',
  servicesEvidance: '/services/guide',
  contractOnService: '/services/contract-procedures',
  search: '/services/search',
} as const;

export const LEGACY_ROUTE_REDIRECTS: ReadonlyArray<{ from: string; to: string }> = [
  { from: '/about-us', to: ROUTES.aboutCompany },
  { from: '/about-company', to: ROUTES.aboutCompany },
  { from: '/an-elsherka', to: ROUTES.aboutCompany },
  { from: '/vision-and-message', to: ROUTES.visionAndMessage },
  { from: '/organization-structure', to: ROUTES.organizationStructure },
  { from: '/information-technology-of-company', to: ROUTES.informationTechnologyOfCompany },
  { from: '/contracts-regulation', to: ROUTES.contractsRegulation },
  { from: '/company-achievements', to: ROUTES.companyAchievements },
  { from: '/branch-of-company', to: ROUTES.branches },
  { from: '/advice-and-contact', to: ROUTES.adviceAndContact },
  { from: '/contract-and-sell', to: ROUTES.contractsRegulation },
  { from: '/company-achivement', to: ROUTES.companyAchievements },
  { from: '/adviceAndContact', to: ROUTES.adviceAndContact },
  { from: '/cyber-security-guidelines', to: ROUTES.cyberSecurityGuidelines },
  { from: '/for-kids-and-women', to: ROUTES.forKidsAndWomen },
  { from: '/forKidsAndWomen', to: ROUTES.forKidsAndWomen },
  { from: '/forKids', to: ROUTES.forKidsAndWomen },
  { from: '/toWomen', to: ROUTES.forKidsAndWomen },
  { from: '/lab-of-company-water', to: ROUTES.labOfCompanyWater },
  { from: '/refining-water', to: ROUTES.refiningWater },
  { from: '/central-water-lab', to: ROUTES.labOfCompanyWater },
  { from: '/sewage-treatment', to: ROUTES.sewageTreatment },
  { from: '/safe-sewage-disposal', to: ROUTES.safeSewageDisposal },
  { from: '/save-sewage-network', to: ROUTES.saveSewageNetwork },
  { from: '/industrial-waste', to: ROUTES.industrialWaste },
  { from: '/industrial-waste-role', to: ROUTES.industrialWasteRole },
  { from: '/Riddence-waste-water', to: ROUTES.safeSewageDisposal },
  { from: '/save-web-waste-water', to: ROUTES.saveSewageNetwork },
  { from: '/manufactring-waste', to: ROUTES.industrialWaste },
  { from: '/waste-water-in-manufactring', to: ROUTES.industrialWasteRole },
  { from: '/news-company', to: ROUTES.newsArchive },
  { from: '/news-archive', to: ROUTES.newsArchive },
  { from: '/projects-company', to: ROUTES.projectsArchive },
  { from: '/projects-archive', to: ROUTES.projectsArchive },
  { from: '/tenders-archive', to: ROUTES.tendersArchive },
  { from: '/allTenders', to: ROUTES.tendersArchive },
  { from: '/alltenders', to: ROUTES.tendersArchive },
  { from: '/hotline125', to: ROUTES.hotlineApp },
  { from: '/readme', to: ROUTES.myReadingApp },
  { from: '/traning-of-company', to: ROUTES.trainingOfCompany },
  { from: '/Customer-Charter', to: ROUTES.customerCharter },
  { from: '/result_of_worker', to: ROUTES.resultOfWorker },
  { from: '/Services-Evidance', to: ROUTES.servicesEvidance },
  { from: '/Contract-On-Service', to: ROUTES.contractOnService },
  { from: '/elslookElwazefy', to: ROUTES.professionalConduct },
  { from: '/general-admin-training', to: ROUTES.generalAdminTraining },
  { from: '/training', to: ROUTES.generalAdminTraining },
  { from: '/nabza-an-daam-elnazaha', to: ROUTES.integritySupportOverview },
  { from: '/abrz-amaal-daam-elnazaha', to: ROUTES.integritySupportHighlights },
  { from: '/professional-conduct', to: ROUTES.professionalConduct },
  { from: '/call-center', to: ROUTES.callCenter },
  { from: '/hotline-app', to: ROUTES.hotlineApp },
  { from: '/search', to: ROUTES.search },
  { from: '/my-reading-app', to: ROUTES.myReadingApp },
  { from: '/customer-charter', to: ROUTES.customerCharter },
  { from: '/services-evidance', to: ROUTES.servicesEvidance },
  { from: '/contract-on-service', to: ROUTES.contractOnService },
  { from: '/provide-request', to: ROUTES.provideRequest },
  { from: '/provide-complaine', to: ROUTES.provideComplaine },
  { from: '/services', to: ROUTES.callCenter },
  { from: '/jobs-and-competition', to: ROUTES.jobsAndCompetition },
  { from: '/result-of-worker', to: ROUTES.resultOfWorker },
  { from: '/careers', to: ROUTES.jobsAndCompetition },
] as const;
