import { useEffect, useState } from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import { useSiteLanguage } from '../context/SiteLanguageContext';

const industrialWasteParagraphs = [
  {
    ar: 'مع التقدم الصناعي لكثير من دول العالم وازدياد عدد المنشأت الصناعية في معظم دول العالم النامي والمتقدم ، ظهرت مشكلة التخلص من المخلفات الصناعية السائلة الناتجة عن النشاط الصناعي ، واتجهت كثير من الشركات الصناعية الي التخلص من مخلفاتها السائلة بصرفها الي المجاري العمومية ( شبكات الصرف الصحي ) ولذلك فمن الضروري مراقبة عمليات صرف أية مخلفات صناعية وألا تسمح السلطات الرقابية بصرف أية مياه صرف صناعية على الشبكة العمومية قبل معرفة كافة خصائص هذه المياه ومدى قدرة شبكة الصرف علي استيعابها ، بالاضافة الى معرفة تأثير ومدى خطورة صرف المركبات المختلفة الموجودة في هذه المياه على شبكات الصرف الصحي وذلك علي المدى القريب والمدى البعيد',
    en: 'With industrial progress across many developed and developing countries and the increasing number of industrial facilities, the problem of disposing of liquid industrial waste generated by industrial activity has emerged. Many industrial companies have turned to discharging their liquid waste into public sewers, so it has become necessary to monitor any industrial discharge and prevent release into the public network before identifying its characteristics, the network’s ability to receive it, and the risks posed by the compounds it contains in both the short and long term.'
  },
  {
    ar: 'إن اهتمام المجتمع الحقيقي بالبيئة على المدى الطويل مطلوب لتحقيق تغيير في مفهوم العامة للحفاظ على البيئة من أجل التنمية المستدامة',
    en: 'Genuine long-term community interest in the environment is necessary to change public awareness and protect the environment for sustainable development.'
  },
  {
    ar: 'ومياه الصرف الصناعي يختلف وضعها من صناعة لأخرى نتيجة لاختلاف المواد الأولية اللازمة للصناعة والمواد الناتجة أو المصنعة',
    en: 'Industrial wastewater differs from one industry to another according to the raw materials used and the resulting or manufactured products.'
  },
  {
    ar: 'إن التصنيف النهائى للملوثات من حيث كونها مطابقة أو غير مطابقة يعتمد علي دراسة نظام الصرف الصحى( محطات المعالجة وشبكات الصرف الصحي ).',
    en: 'The final classification of pollutants as compliant or non-compliant depends on a study of the wastewater system, including treatment plants and sewer networks.'
  },
];

const treatmentStationParagraphs = [
  {
    ar: 'باختصار يتم في المدن والقرى تجميع مياه الصرف الصحي في خطوط يتم توجيهها الى محطات المعالجة التي هي على نوعين :',
    en: 'In brief, wastewater in cities and villages is collected through pipelines and directed to treatment plants, which are of two types:'
  },
  { ar: 'المحطات المفتوحة', en: 'Open plants' },
  { ar: 'الطريقة المغلقة', en: 'Closed systems' },
  {
    ar: 'للنظامين الاحجام المناسبة والتصميم المناسب حسب كميات المياه المطلوب معالجتها يومياً .',
    en: 'Both systems are designed with appropriate sizes according to the quantity of water to be treated each day.'
  },
];

const pollutantsParagraphs = [
  {
    ar: 'المواد الصلبة العالقة – المواد المغذية – الملوثات ذات الأهمية القصوى – المواد العضوية صعبة التحلل- المعادن الثقيلة – الأملاح الغير العضوية الذائبة',
    en: 'Suspended solids, nutrients, priority pollutants, hard-to-degrade organic materials, heavy metals, and dissolved inorganic salts.'
  },
];

const treatmentMethodsParagraphs = [
  { ar: 'عمليات المعالجة الفيزيائية', en: 'Physical treatment processes' },
  { ar: 'عمليات المعالجة البيولوجية', en: 'Biological treatment processes' },
  { ar: 'عمليات المعالجة الكيميائية', en: 'Chemical treatment processes' },
  {
    ar: 'إن دور الإدارة العامة للصرف الصناعي بشركة مياه الشرب والصرف الصحي بأسيوط والوادي الجديد لا يقتصر على الإشراف على المنشآت بجميع أنواعها ( صناعية – تجارية – سياحية – طبية ،،،،،،،،،،)ولكن أيضا يكمن في الحفاظ على شبكات الصرف الصحى من أجل غدا أفضل',
    en: 'The role of the General Department of Industrial Wastewater at Assiut and New Valley Water and Wastewater Company is not limited to supervising facilities of all kinds, including industrial, commercial, tourism, and medical facilities, but also includes protecting sewer networks for a better tomorrow.'
  },
];

function IndustrialWastePage() {
  const { language } = useSiteLanguage();
  const isEnglish = language === 'en';
  const t = (arabic: string, english: string) => (isEnglish ? english : arabic);
  const paragraphAlignmentClass = isEnglish ? 'text-left' : 'text-right';
  const figureLayoutClass = isEnglish
    ? 'mb-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:float-right md:mb-3 md:mr-6 md:w-[36%]'
    : 'mb-4 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm md:float-left md:mb-3 md:ml-6 md:w-[36%]';
  const [lightboxImage, setLightboxImage] = useState<{
    src: string;
    alt: string;
  } | null>(null);

  const openLightbox = (image: { src: string; alt: string }) => {
    setLightboxImage(image);
  };

  const closeLightbox = () => {
    setLightboxImage(null);
  };

  useEffect(() => {
    if (!lightboxImage) return;

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        closeLightbox();
      }
    };

    document.addEventListener('keydown', onKeyDown);
    document.body.style.overflow = 'hidden';

    return () => {
      document.removeEventListener('keydown', onKeyDown);
      document.body.style.overflow = '';
    };
  }, [lightboxImage]);

  return (
    <>
      <Header />
      <main className="bg-[radial-gradient(circle_at_top,_rgba(17,112,176,0.08),_transparent_50%)]" dir={isEnglish ? 'ltr' : 'rtl'}>
        <div className="container mx-auto max-w-7xl px-4 py-8 md:py-10">
          <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_20px_55px_rgba(2,6,23,0.08)]">
            <div className="bg-gradient-to-l from-[#0a3555] to-[#1170b0] px-6 py-7 text-white sm:px-8">
              <h1 className="text-2xl font-extrabold sm:text-3xl">{t('الصرف الصناعي', 'Industrial Wastewater')}</h1>
            </div>

            <div className="space-y-6 px-4 py-6 sm:px-8 sm:py-8">
              <article className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5 shadow-sm sm:p-6">
                <h2 className="text-xl font-extrabold text-[#0a3555] sm:text-2xl">{t('نبذه عن الصرف الصناعي', 'Overview of industrial wastewater')}</h2>
                <div className="mt-4 flow-root">
                  <figure className={figureLayoutClass}>
                    <img decoding="async"
                      src="/images/prosses-water/manufactring-waste1.webp"
                      alt={t('نبذه عن الصرف الصناعي', 'Overview of industrial wastewater')}
                      loading="lazy"
                      onClick={() =>
                        openLightbox({
                          src: '/images/prosses-water/manufactring-waste1.webp',
                          alt: t('نبذه عن الصرف الصناعي', 'Overview of industrial wastewater'),
                        })
                      }
                      title={t('اضغط للتكبير', 'Click to enlarge')}
                      className="h-full w-full cursor-zoom-in object-cover"
                    />
                  </figure>
                  <div className="space-y-4">
                    {industrialWasteParagraphs.map((paragraph) => (
                      <p key={paragraph.ar} className={`${paragraphAlignmentClass} text-base leading-8 text-slate-700`}>
                        {isEnglish ? paragraph.en : paragraph.ar}
                      </p>
                    ))}
                  </div>
                </div>
              </article>

              <article className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5 shadow-sm sm:p-6">
                <h2 className="text-xl font-extrabold text-[#0a3555] sm:text-2xl">{t('محطات المعالجه', 'Treatment plants')}</h2>
                <div className="mt-4 flow-root">
                  <figure className={figureLayoutClass}>
                    <img decoding="async"
                      src="/images/prosses-water/manufactring-waste2.webp"
                      alt={t('محطات المعالجه', 'Treatment plants')}
                      loading="lazy"
                      onClick={() =>
                        openLightbox({
                          src: '/images/prosses-water/manufactring-waste2.webp',
                          alt: t('محطات المعالجه', 'Treatment plants'),
                        })
                      }
                      title={t('اضغط للتكبير', 'Click to enlarge')}
                      className="h-full w-full cursor-zoom-in object-cover"
                    />
                  </figure>
                  <div className="space-y-4">
                    {treatmentStationParagraphs.map((paragraph) => (
                      <p key={paragraph.ar} className={`${paragraphAlignmentClass} text-base leading-8 text-slate-700`}>
                        {isEnglish ? paragraph.en : paragraph.ar}
                      </p>
                    ))}
                  </div>
                </div>
              </article>

              <article className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5 shadow-sm sm:p-6">
                <h2 className="text-xl font-extrabold text-[#0a3555] sm:text-2xl">{t('الملوثات فى مياه الصرف الصناعي', 'Pollutants in industrial wastewater')}</h2>
                <div className="mt-4 flow-root">
                  <figure className={figureLayoutClass}>
                    <img decoding="async"
                      src="/images/prosses-water/manufactring-waste3.webp"
                      alt={t('الملوثات فى مياه الصرف الصناعي', 'Pollutants in industrial wastewater')}
                      loading="lazy"
                      onClick={() =>
                        openLightbox({
                          src: '/images/prosses-water/manufactring-waste3.webp',
                          alt: t('الملوثات فى مياه الصرف الصناعي', 'Pollutants in industrial wastewater'),
                        })
                      }
                      title={t('اضغط للتكبير', 'Click to enlarge')}
                      className="h-full w-full cursor-zoom-in object-cover"
                    />
                  </figure>
                  <div className="space-y-4">
                    {pollutantsParagraphs.map((paragraph) => (
                      <p
                        key={paragraph.ar}
                        className={`${paragraphAlignmentClass} text-base leading-8 text-slate-700 md:text-lg md:leading-[4rem]`}
                      >
                        {isEnglish ? paragraph.en : paragraph.ar}
                      </p>
                    ))}
                  </div>
                </div>
              </article>

              <article className="rounded-2xl border border-slate-200 bg-slate-50/70 p-5 shadow-sm sm:p-6">
                <h2 className="text-xl font-extrabold text-[#0a3555] sm:text-2xl">{t('الطرق الشائعة لمعالجة مياه الصرف الصناعي', 'Common methods for industrial wastewater treatment')}</h2>
                <div className="mt-4 flow-root">
                  <figure className={figureLayoutClass}>
                    <img decoding="async"
                      src="/images/prosses-water/manufactring-waste4.webp"
                      alt={t('الطرق الشائعة لمعالجة مياه الصرف الصناعي', 'Common methods for industrial wastewater treatment')}
                      loading="lazy"
                      onClick={() =>
                        openLightbox({
                          src: '/images/prosses-water/manufactring-waste4.webp',
                          alt: t('الطرق الشائعة لمعالجة مياه الصرف الصناعي', 'Common methods for industrial wastewater treatment'),
                        })
                      }
                      title={t('اضغط للتكبير', 'Click to enlarge')}
                      className="h-full w-full cursor-zoom-in object-cover"
                    />
                  </figure>
                  <div className="space-y-4">
                    {treatmentMethodsParagraphs.map((paragraph) => (
                      <p key={paragraph.ar} className={`${paragraphAlignmentClass} text-base leading-8 text-slate-700`}>
                        {isEnglish ? paragraph.en : paragraph.ar}
                      </p>
                    ))}
                  </div>
                </div>
              </article>
            </div>
          </section>
        </div>
      </main>
      {lightboxImage && (
        <div
          className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/85 px-2 py-4 sm:px-4 sm:py-6"
          onClick={closeLightbox}
          role="presentation"
        >
          <div
            className="relative max-h-full max-w-[96vw]"
            onClick={(event) => event.stopPropagation()}
            role="dialog"
            aria-modal="true"
            aria-label={lightboxImage.alt}
          >
            <button
              type="button"
              onClick={closeLightbox}
              className="absolute right-3 top-3 rounded-full bg-white/90 px-3 py-1 text-sm font-bold text-slate-900 shadow"
            >
              {t('إغلاق', 'Close')}
            </button>
            <img loading="lazy" decoding="async"
              src={lightboxImage.src}
              alt={lightboxImage.alt}
              className="max-h-[92vh] w-auto max-w-full rounded-2xl border border-white/20 bg-white object-contain shadow-2xl"
            />
          </div>
        </div>
      )}
      <Footer />
    </>
  );
}

export default IndustrialWastePage;
